version: v1.0
fail_fast: true
is_cypress: false
plan: standard-2

triggers:
  - event: branch
    branch_name: main

envs:
  - key: PRODUCT
    value: cal

commands:
  - checkout
  - git fsck --full
  - git repack -a -d
  - git remote add neeto-${PRODUCT}-api "https://x-access-token:${GITHUB_PAT}@github.com/neeto${PRODUCT}apis/neeto-${PRODUCT}-api.git"
  - git push neeto-${PRODUCT}-api HEAD:main --force
