openapi: 3.0.0
servers:
  - description: NeetoCI APIs
    url: https://{your-subdomain}.neetoci.com/api/v2
    variables:
      your-subdomain:
        default: neetozone
        description: Your workspace's subdomain.

info:
  description: NeetoCI offers APIs to create CI jobs and manage continuous integration workflows. To use the APIs, you will need an API key.
  title: NeetoCI APIs

tags:
  - name: CI Jobs
    description: APIs to create and manage CI jobs in the workspace.

paths:
  /ci-jobs:
    post:
      summary: Create a CI job
      tags:
        - CI Jobs
      description: This API allows you to create a CI job for a specific project and branch with a specified workflow.
      parameters:
        - in: header
          name: X-Api-Key
          description: You can generate an API key from the NeetoCI API Keys dashboard. [X-Api-Key for neetozone](https://start.1password.com/open/i?a=AD3QJO5IAVBUDLQ7W5XSH62T3Y&v=362hgmqklfeypggznttlaolvjq&i=y4w2ibkkggepmf4dv75lbciiqm&h=neetozone.1password.com).
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/ci-job-trigger.yaml#/components/schemas/ci_job_trigger_request'
      responses:
        '201':
          description: Created - CI job created successfully.
          content:
            application/json:
              schema:
                $ref: '../schemas/ci-job-trigger.yaml#/components/schemas/ci_job_trigger_response'
        '400':
          description: Bad Request - Missing/Invalid parameters.
        '401':
          description: Unauthorized - Invalid API key.
        '500':
          description: Internal server error.
