openapi: 3.0.0
servers:
  - description: NeetoCal APIs
    url: https://{workspace}.neetocal.com/api/external/v1
    variables:
      workspace:
        default: spinkart
        description: Your workspace's subdomain

info:
  description: NeetoCal offers APIs to manage meeting duration options for scheduling links. To use the APIs, [you will need an API key.](https://help.neetocal.com/articles/api-keys)
  title: NeetoCal Meeting Durations APIs

tags:
  - name: Meeting Durations
    description: APIs to manage meeting duration options for scheduling links.

paths:
  /meetings/{meeting_sid}/durations:
    get:
      summary: List all durations for a meeting
      tags:
        - Meeting Durations
      description: This API allows to get a list of all duration options configured for a specific meeting.
      parameters:
        - in: header
          name: X-Api-Key
          description: You can generate an API key from the [NeetoCal API Keys dashboard](https://help.neetocal.com/articles/api-keys).
          required: true
          schema:
            type: string
        - in: path
          name: meeting_sid
          description: >
            The unique identifier (SID) of the scheduling link you want to use.
            You can get `sid` in different ways. Visit the scheduling link page and then click
            on "Settings" > "Show SID". That will give you `sid`.
            You can also get this from the response of the [List all scheduling links](/api-reference/scheduling-links/list-meetings) endpoint,
            where it appears as the `sid` property for each scheduling link in the response.
          required: true
          schema:
            type: string
            example: "vj5pgkh"
      responses:
        "200":
          description: OK - Request succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  durations:
                    type: array
                    items:
                      $ref: "../schemas/duration.yaml#/components/schemas/duration"
                    description: List of all duration options configured for the meeting
        "400":
          description: Bad Request - Invalid meeting SID
        "401":
          description: Unauthorized - Invalid API key
        "404":
          description: Not Found - Meeting not found
        "500":
          description: Internal server error
    post:
      summary: Create a new duration
      tags:
        - Meeting Durations
      description: This API allows to create a new duration option for a specific meeting.
      parameters:
        - in: header
          name: X-Api-Key
          description: You can generate an API key from the [NeetoCal API Keys dashboard](https://help.neetocal.com/articles/api-keys).
          required: true
          schema:
            type: string
        - in: path
          name: meeting_sid
          description: >
            The unique identifier (SID) of the scheduling link you want to use.
            You can get `sid` in different ways. Visit the scheduling link page and then click
            on "Settings" > "Show SID". That will give you `sid`.
            You can also get this from the response of the [List all scheduling links](/api-reference/scheduling-links/list-meetings) endpoint,
            where it appears as the `sid` property for each scheduling link in the response.
          required: true
          schema:
            type: string
            example: "vj5pgkh"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "../schemas/duration.yaml#/components/schemas/duration_create_request"
      responses:
        "200":
          description: OK - Request succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Duration created successfully"
                  duration:
                    $ref: "../schemas/duration.yaml#/components/schemas/duration"
        "400":
          description: Bad Request - Invalid meeting SID, duration value, or duration out of range
        "401":
          description: Unauthorized - Invalid API key
        "404":
          description: Not Found - Meeting not found
        "409":
          description: Conflict - Only one duration can be default
        "500":
          description: Internal server error

  /meetings/{meeting_sid}/durations/{id}:
    get:
      summary: Get a specific duration
      tags:
        - Meeting Durations
      description: This API allows to get details of a specific duration option for a meeting.
      parameters:
        - in: header
          name: X-Api-Key
          description: You can generate an API key from the [NeetoCal API Keys dashboard](https://help.neetocal.com/articles/api-keys).
          required: true
          schema:
            type: string
        - in: path
          name: meeting_sid
          description: >
            The unique identifier (SID) of the scheduling link you want to use.
            You can get `sid` in different ways. Visit the scheduling link page and then click
            on "Settings" > "Show SID". That will give you `sid`.
            You can also get this from the response of the [List all scheduling links](/api-reference/scheduling-links/list-meetings) endpoint,
            where it appears as the `sid` property for each scheduling link in the response.
          required: true
          schema:
            type: string
            example: "vj5pgkh"
        - in: path
          name: id
          description: >
            The unique identifier of the duration. You can get this `id` from the response of the
            [List durations for a meeting](/api-reference/scheduling-links/durations/list-durations) endpoint,
            where it appears as the `id` property for each duration in the response.
          required: true
          schema:
            type: string
            example: "4ece6b6b-4b5f-4c15-9122-a85af189198c"
      responses:
        "200":
          description: OK - Request succeeded
          content:
            application/json:
              schema:
                $ref: "../schemas/duration.yaml#/components/schemas/duration"
        "400":
          description: Bad Request - Invalid meeting SID or duration ID
        "401":
          description: Unauthorized - Invalid API key
        "404":
          description: Not Found - Meeting or duration not found
        "500":
          description: Internal server error
    put:
      summary: Update a duration
      tags:
        - Meeting Durations
      description: This API allows to update an existing duration option for a meeting.
      parameters:
        - in: header
          name: X-Api-Key
          description: You can generate an API key from the [NeetoCal API Keys dashboard](https://help.neetocal.com/articles/api-keys).
          required: true
          schema:
            type: string
        - in: path
          name: meeting_sid
          description: >
            The unique identifier (SID) of the scheduling link you want to use.
            You can get `sid` in different ways. Visit the scheduling link page and then click
            on "Settings" > "Show SID". That will give you `sid`.
            You can also get this from the response of the [List all scheduling links](/api-reference/scheduling-links/list-meetings) endpoint,
            where it appears as the `sid` property for each scheduling link in the response.
          required: true
          schema:
            type: string
            example: "vj5pgkh"
        - in: path
          name: id
          description: >
            The unique identifier of the duration. You can get this `id` from the response of the
            [List durations for a meeting](/api-reference/scheduling-links/durations/list-durations) endpoint,
            where it appears as the `id` property for each duration in the response.
          required: true
          schema:
            type: string
            example: "4ece6b6b-4b5f-4c15-9122-a85af189198c"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../schemas/duration.yaml#/components/schemas/duration_update_request"
      responses:
        "200":
          description: OK - Request succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Duration updated successfully"
                  duration:
                    $ref: "../schemas/duration.yaml#/components/schemas/duration"
        "400":
          description: Bad Request - Invalid meeting SID, duration ID, duration value, or duration out of range
        "401":
          description: Unauthorized - Invalid API key
        "404":
          description: Not Found - Meeting or duration not found
        "409":
          description: Conflict - Only one duration can be default
        "500":
          description: Internal server error
    delete:
      summary: Delete a duration
      tags:
        - Meeting Durations
      description: This API allows to remove a duration option from a meeting.
      parameters:
        - in: header
          name: X-Api-Key
          description: You can generate an API key from the [NeetoCal API Keys dashboard](https://help.neetocal.com/articles/api-keys).
          required: true
          schema:
            type: string
        - in: path
          name: meeting_sid
          description: >
            The unique identifier (SID) of the scheduling link you want to use.
            You can get `sid` in different ways. Visit the scheduling link page and then click
            on "Settings" > "Show SID". That will give you `sid`.
            You can also get this from the response of the [List all scheduling links](/api-reference/scheduling-links/list-meetings) endpoint,
            where it appears as the `sid` property for each scheduling link in the response.
          required: true
          schema:
            type: string
            example: "vj5pgkh"
        - in: path
          name: id
          description: >
            The unique identifier of the duration. You can get this `id` from the response of the
            [List durations for a meeting](/api-reference/scheduling-links/durations/list-durations) endpoint,
            where it appears as the `id` property for each duration in the response.
          required: true
          schema:
            type: string
            example: "4ece6b6b-4b5f-4c15-9122-a85af189198c"
      responses:
        "200":
          description: OK - Request succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Duration destroyed successfully"
        "400":
          description: Bad Request - Invalid meeting SID or duration ID
        "401":
          description: Unauthorized - Invalid API key
        "404":
          description: Not Found - Meeting or duration not found
        "409":
          description: Conflict - Cannot delete the last remaining duration
        "500":
          description: Internal server error
