openapi: 3.0.0
servers:
  - description: NeetoCal APIs
    url: https://{workspace}.neetocal.com/api/external/v1
    variables:
      workspace:
        default: spinkart
        description: Your workspace's subdomain

info:
  description: NeetoCal offers APIs to manage bookings from external channels. To use the APIs, [you will need an API key.](https://help.neetocal.com/articles/api-keys)
  title: NeetoCal Meetings APIs

tags:
  - name: Scheduling links
    description: APIs to create and manage scheduling links.

paths:
  /meetings:
    get:
      summary: List all scheduling links
      tags:
        - Scheduling links
      description: This API allows to get a list of scheduling links in a workspace.
      parameters:
        - in: header
          name: X-Api-Key
          description: Bearer token for API access.
          required: true
          schema:
            type: string
        - in: query
          name: page_number
          description: Page number. The default value is 1.
          required: false
          schema:
            type: number
        - in: query
          name: page_size
          description: Number of bookings to receive. The default value is 30.
          required: false
          schema:
            type: number
      responses:
        "200":
          description: OK - Request succeeded
          content:
            application/json:
              schema:
                $ref: "../schemas/meeting.yaml#/components/schemas/meeting_list_response"
        "400":
          description: Bad Request - Missing/Invalid parameters
        "401":
          description: Unauthorized - Invalid API key
        "500":
          description: Internal server error

    post:
      summary: Create a scheduling link
      tags:
        - Scheduling links
      description: This API allows to create a scheduling link.
      parameters:
        - in: header
          name: X-Api-Key
          description: You can generate an API key from the [NeetoCal API Keys dashboard](https://help.neetocal.com/articles/api-keys).
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                slug:
                  type: string
                  description: Slug of the scheduling link. This value should be unique.
                  example: "meeting-with-oliver-smith"
                name:
                  type: string
                  description: New name of the scheduling link.
                  example: "Meeting with Oliver Smith"
                description:
                  type: string
                  description: Description of the scheduling link.
                  example: "Discuss project updates"
                hosts:
                  type: array
                  items:
                    type: string
                  description: Emails of the hosts of scheduling link in array format.
                  example: ["oliver@example.com", "jane@example.com"]
                kind:
                  type: string
                  enum: ["one_on_one", "round_robin", "multihost", "grouped"]
                  description: Kind of scheduling link.
                  default: "one_on_one"
                duration:
                  type: integer
                  description: Duration of the scheduling link in minutes.
                  example: 30
                start_time_increment:
                  type: integer
                  description: Start time increment for the scheduling link in minutes. Defaults to 30.
                  example: 30
              required:
                - slug
                - name
                - hosts
                - duration
      responses:
        "200":
          description: OK - Request succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Meeting created successfully"
                  meeting:
                    $ref: "../schemas/meeting.yaml#/components/schemas/meeting"
        "400":
          description: Bad Request - Missing/Invalid parameters
        "401":
          description: Unauthorized - Invalid API key
        "500":
          description: Internal server error

  /meetings/{meeting_sid}:
    get:
      summary: Get scheduling link details
      tags:
        - Scheduling links
      description: This API allows you to fetch details of a specific scheduling link by its SID.
      parameters:
        - in: header
          name: X-Api-Key
          description: You can generate an API key from the [NeetoCal API Keys dashboard](https://help.neetocal.com/articles/api-keys).
          required: true
          schema:
            type: string
        - in: path
          name: meeting_sid
          description: The unique SID of the scheduling link you want to fetch.
            You can get `sid` in different ways. Visit the scheduling link page and then click
            on "Settings" > "Show SID". That will give you `sid`.
            The other way you can get `sid` is by listing scheduling links using our `List all scheduling links` API.
            Here you will see `sid` for each scheduling link.
          required: true
          schema:
            type: string
            example: vj5pgkh
      responses:
        "200":
          description: OK - Request succeeded
          content:
            application/json:
              schema:
                $ref: "../schemas/meeting.yaml#/components/schemas/meeting"
        "400":
          description: Bad Request - Missing/Invalid parameters
        "401":
          description: Unauthorized - Invalid API key
        "404":
          description: Not Found - Meeting not found
        "500":
          description: Internal server error
    patch:
      summary: Update a scheduling link
      tags:
        - Scheduling links
      description: This API allows to update a scheduling link.
      parameters:
        - in: header
          name: X-Api-Key
          description: You can generate an API key from the [NeetoCal API Keys dashboard](https://help.neetocal.com/articles/api-keys).
          required: true
          schema:
            type: string
        - in: path
          name: meeting_sid
          description: Id of the scheduling link you want to update.
          required: true
          schema:
            type: string
          example: vj5pgkh
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                slug:
                  type: string
                  description: New slug of the scheduling link. This value should be unique.
                  example: "meeting-with-oliver-smith-new"
                name:
                  type: string
                  description: New name of the scheduling link.
                  example: "Meeting with Oliver Smith"
                description:
                  type: string
                  description: Description of the scheduling link.
                  example: "Discuss project updates"
                hosts:
                  type: array
                  items:
                    type: string
                  description: Emails of the hosts of scheduling link in array format.
                  example: ["oliver@example.com", "jane@example.com"]
                kind:
                  type: string
                  enum: ["one_on_one", "round_robin", "multihost", "grouped"]
                  description: Kind of scheduling link.
                  default: "one_on_one"
                duration:
                  type: integer
                  description: Duration of the scheduling link in minutes.
                  example: 30
                start_time_increment:
                  type: integer
                  description: Start time increment for the scheduling link in minutes. Defaults to 30.
                  example: 30
              required:
                - hosts
      responses:
        "200":
          description: OK - Request succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  meeting:
                    $ref: "../schemas/meeting.yaml#/components/schemas/meeting"
        "400":
          description: Bad Request - Missing/Invalid parameters
        "401":
          description: Unauthorized - Invalid API key
        "500":
          description: Internal server error

  /meetings/{meeting_sid}/create_one_off_link:
    post:
      summary: Create a One-time scheduling link
      tags:
        - Scheduling links
      description: This API allows to create a One-time scheduling link.
      parameters:
        - in: header
          name: X-Api-Key
          description: You can generate an API key from the [NeetoCal API Keys dashboard](https://help.neetocal.com/articles/api-keys).
          required: true
          schema:
            type: string
        - in: path
          name: meeting_sid
          description: >
            You need to pass the `sid` of the scheduling link to get one-time scheduling link.
            You can get `sid` in different ways. Visit the scheduling link page and then click
            on "Settings" > "Show SID". That will give you `sid`.
            The other way you can get `sid` is by listing scheduling links using our `List all scheduling links` API.
            Here you will see `sid` for each scheduling link.
          required: true
          schema:
            type: string
          example: vj5pgkh
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: OK - Request succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  slug:
                    type: string
                  url:
                    type: string
              example:
                slug: "one-off-c5530bc7c9ab"
                url: "https://spinkart.neetocal.com/one-off-c5530bc7c9ab"
        "400":
          description: Bad Request - Missing/Invalid parameters
        "401":
          description: Unauthorized - Invalid API key
        "500":
          description: Internal server error

  /meeting_templates:
    get:
      summary: List all meeting templates
      tags:
        - Scheduling links
      description: This API allows you to get a list of meeting templates in a workspace.
      parameters:
        - in: header
          name: X-Api-Key
          description: Bearer token for API access.
          required: true
          schema:
            type: string
        - in: query
          name: page_number
          description: Page number. The default value is 1.
          required: false
          schema:
            type: number
        - in: query
          name: page_size
          description: Number of templates to receive. The default value is 30.
          required: false
          schema:
            type: number
      responses:
        "200":
          description: OK - Request succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  templates:
                    type: array
                    items:
                      $ref: "../schemas/meeting.yaml#/components/schemas/meeting"
                    description: List of meeting templates.
                  pagination:
                    $ref: "../schemas/common.yaml#/components/schemas/pagination"
              example:
                templates:
                  - id: "cc98d282-4cf6-414d-ba58-53fa94b9bca3"
                    sid: "8r3rs2k"
                    name: "Meeting with Oliver Smith"
                    slug: "meeting-with-oliver-smith"
                    description: "Schedule a one-on-one meeting with Oliver Smith."
                    kind: "one_on_one"
                    duration: 15
                    disabled: false
                    spot: "jitsi"
                    spot_in_person_location: null
                    spot_custom_text: null
                    spot_phone_call_number: null
                    is_template: true
                    schedulable_range_type: "number_of_days_into_the_future"
                    schedulable_range_value: "60"
                    lead_time: 240
                    start_time_increment: 30
                    created_at: "2025-08-14T07:26:14.909Z"
                    updated_at: "2025-08-14T07:26:14.909Z"
                    deleted_at: null
                    is_multiple_spots_allowed: false
                    is_multiple_durations_allowed: false
                    conditional_pricing_enabled: false
                    is_email_reminders_enabled: true
                    is_sms_reminders_enabled: false
                    organization_id: "dfc0e240-15c1-4483-a76e-8d8feb3c162b"
                    rescheduling_lead_time: 0
                    cancellation_lead_time: 0
                    booking_modification_allowed: true
                    cancellation_too_late_notice: null
                    cancellation_policy: null
                    rescheduling_too_late_notice: null
                    pre_booking_allowed: false
                    original_price_enabled: false
                    original_price: null
                    fees: []
                    durations_possible: []
                    durations: []
                    spots: []
                pagination:
                  total_records: 1
                  total_pages: 1
                  current_page_number: 1
                  page_size: 30
        "400":
          description: Bad Request - Missing/Invalid parameters
        "401":
          description: Unauthorized - Invalid API key
        "500":
          description: Internal server error
