openapi: 3.0.0
servers:
  - description: NeetoCal APIs
    url: https://{workspace}.neetocal.com/api/external/v1
    variables:
      workspace:
        default: spinkart
        description: Your workspace's subdomain

info:
  description: NeetoCal offers APIs to manage bookings from external channels. To use the APIs, [you will need an API key.](https://help.neetocal.com/articles/api-keys)
  title: NeetoCal Packages APIs

tags:
  - name: Packages
    description: APIs to manage packages of the workspace.

paths:
  /packages:
    get:
      summary: List all packages
      tags:
        - Packages
      description: This API allows to list all packages.
      parameters:
        - in: header
          name: X-Api-Key
          description: Bearer token for API access.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK - Request succeeded
          content:
            application/json:
              schema:
                $ref: '../schemas/package.yaml#/components/schemas/package_list_response'
        '400':
          description: Bad Request - Missing/Invalid parameters
        '401':
          description: Unauthorized - Invalid API key
        '500':
          description: Internal server error

  /packages/{package_id}:
    get:
      summary: Get a package
      tags:
        - Packages
      description: This API allows to get a package.
      parameters:
        - in: header
          name: X-Api-Key
          description: Bearer token for API access.
          required: true
          schema:
            type: string
        - in: path
          name: package_id
          description: Id of the package to retrieve.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK - Request succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  package:
                    $ref: '../schemas/package.yaml#/components/schemas/package'
        '400':
          description: Bad Request - Missing/Invalid parameters
        '401':
          description: Unauthorized - Invalid API key
        '500':
          description: Internal server error
